version: '3.1'
services:
  jenkins:
    build:
      context: ./
      dockerfile: jenkins.dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $HOME/jenkins_home:/var/jenkins_home
      - $HOME/ansible:/etc/ansible
  nagios:
    image: jasonrivers/nagios:latest
    volumes:
      - ./nagios/plugins/:/opt/Custom-Nagios-Plugins
    ports:
      - "8081:8081"
  nexus:
    image: sonatype/nexus3
    ports:
      - "8082:8082"
