version: '3.1'
services:
  mongo:
    image: mongo:3.6.9-stretch
    command: --smallfiles --auth
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testing
    deploy:
      resources:
        limits:
          memory: 75M
  app:
    build:
      context: ./
    volumes:
      - /logs:/logs
      - ./src/main/java:/app/src/main/java
      - ./src/test/java:/app/src/test/java
      - ./src/main/js:/app/src/main/js
      - ./logs:/app/logs
      - /root/archives:/archives
    ports:
      - "8080:8080"
      - "5005:5005"
      - "35729:35729"
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          memory: 700M
