version: '3.1'
services:
  mongo:
    image: mongo:3.4.20-xenial
    command: --smallfiles --auth
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testing
    volumes:
      - ~/mongo:/data/db


  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./logs:/logs
      - ./db:/db
      - ./:/app/
    ports:
      - "8080:8080"
      - "5005:5005"
      - "35729:35729"
    depends_on:
      - mongo



