version: '3.1'
services:
  mongo:
    image: mongo:3.6.9-stretch
    command: --smallfiles --auth
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testing
  app:
    build:
      context: ./
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
      - "5005:5005"
      - "35729:35729"

