version: "3.1"
services:
  mongo:
    image: mongo:latest
    restart: always
    command: mongod --logpath=/dev/null
    ports:
      - "27017:27017"
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testing
      MONGODB_USER: root
      MONGODB_PASS: testing
      MONGO_INITDB_DATABASE: admin
    ##volumes:
    ##  - ./mongo:/data/db
  frontend:
    image: node:14.3.0-alpine3.10
    ports:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./logs:/logs
      - ./db:/db
      - ./:/app/
    ports:
      - "8080:8080"
      - "5005:5005"
      - "35729:35729"
    depends_on:
      - mongo
