version: '3.1'
services:
  mongo:
    image: mongo:3.6.9-stretch
    command: --smallfiles --auth
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testing
    deploy:
      resources:
        limits:
          memory: 75M
  nagios:
    image: jasonrivers/nagios:latest
    volumes:
      - ./nagios/plugins/:/opt/Custom-Nagios-Plugins
    ports:
      - "8081:80"
    deploy:
      resources:
        limits:
          memory: 100M
  jenkins:
    image: jenkinsci/blueocean:latest
    environment:
      - JENKINS_UC=http://ftp-chi.osuosl.org
    ports:
      - "8082:8080"
  app:
    build:
      context: ./
    volumes:
      - ./src/main/java:/app/src/main/java
      - ./src/test/java:/app/src/test/java
      - ./src/main/js:/app/src/main/js
      - ./logs:/app/logs  
    ports:
      - "8080:8080"
      - "5005:5005"
      - "35729:35729"
    deploy:
      resources:
        limits:
          memory: 700M
