FROM openjdk:7

RUN curl https://raw.githubusercontent.com/nelson54/snippets/master/.git_profile > ~/.bashrc
RUN curl https://raw.githubusercontent.com/nelson54/snippets/master/.vimrc > ~/.vimrc
RUN curl https://raw.githubusercontent.com/nelson54/snippets/master/.tmux.config > ~/.tmux.config

RUN apt-get install -y nodejs git vim tmux

COPY ../build/libs/dominionweb-1.0-SNAPSHOT.jar:/app/dominion.jar

CMD bash