version: '3.1'
services:
  jenkins:
    build:
      context: ../../devops
      dockerfile: jenkins.dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $HOME/jenkins_home:/var/jenkins_home
      - $HOME/ansible:/etc/ansible
  nagios:
    image: jasonrivers/nagios:latest
    volumes:
      - ./nagios/plugins/:/opt/Custom-Nagios-Plugins
    ports:
      - "8081:8081"
  sonarqube:
    image: sonarqube:6.7-community
    ports:
      - "8082:9000"
    volumes:
      - $HOME/.sonar_qube/conf:/opt/sonarqube/conf
      - $HOME/.sonar_qube/data:/opt/sonarqube/data
      - $HOME/.sonar_qube/logs:/opt/sonarqube/logs
      - $HOME/.sonar_qube/extensions:/opt/sonarqube/extensions