DELETE FROM MATCH_PLAYERS WHERE MATCH_ENTITY_ID = 714;
DELETE FROM CARD_TYPE_REFERENCE WHERE GAME_CARDS_ID = 714;
DELETE FROM MATCH WHERE MATCH.ID = 714;

DELETE FROM CARD_TYPE_REFERENCE WHERE name is null;

alter table CARD_TYPE_REFERENCE
    drop column SCORE;

alter table CARD_TYPE_REFERENCE
    drop column ACCOUNT_ID;

alter table CARD_TYPE_REFERENCE
    drop column SCORES_ID;

