---
- hosts: webservers
  remote_user: root
  tasks:
    - name: Enable UFW
      ufw:
        state: enabled
        policy: allow
    - name: open port 80/udp
      ufw:
        rule: allow
        port: 80
        proto: udp
    - name: open port 80/tcp
      ufw:
        rule: allow
        port: 80
        proto: tcp
    - name: open port 9000/udp
      ufw:
        rule: allow
        port: 9000
        proto: udp
    - name: open port 9000/tcp
      ufw:
        rule: allow
        port: 9000
        proto: tcp
    - name: open port 9001/udp
      ufw:
        rule: allow
        port: 9001
        proto: udp
    - name: open port 9001/tcp
      ufw:
        rule: allow
        port: 9001
        proto: tcp