---
- hosts: webservers
  remote_user: root
  tasks:
    - name: checkout
      git:
        repo: 'git@github.com:nelson54/javaminion.git'
        dest: /root/javaminion
    - name: build
      command: docker-compose -f /root/javaminion/docker-compose.yml build
    - name: start
      command: docker-compose -f /root/javaminion/docker-compose.yml up -d
    - name: restart nginx
      command: systemctl restart nginx