---
- hosts: webservers
  remote_user: root
  tasks:
    - name: update packages
      command: apt update -y
    - name: install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - htop
          - tmux
          - vim
          - curl
          - git
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - nginx
          - openjdk-11-jre-headless

    - name: Add Apt signing key on remote server to keyring
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: fingerprint
      command: apt-key fingerprint 0EBFCD88
    - name: add repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
    - name: install docker
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - docker-compose
          - containerd.io
          - nodejs
          - npm
    - name: install sass and gulp
      command: npm install -g sass bower npm-cache
    - name: write the apache config file
      copy:
        src: ../config/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
    - name: ensure apache is running
      service:
        name: nginx
        state: started
    - name: make ssh directory
      file:
        path: /root/.ssh
        state: directory
        mode: 0700
    - name: copy authorized_keys
      copy:
        src: ../config/ssh/authorized_keys
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: 0700
    - name: copy id_rsa
      copy:
        src: ../config/ssh/id_rsa
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: 0600
    - name: copy id_rsa.pub
      copy:
        src: ../config/ssh/id_rsa.pub
        dest: /root/.ssh/id_rsa.pub
        owner: root
        group: root
        mode: 0644
    - name: copy known_hosts
      copy:
        src: ../config/ssh/known_hosts
        dest: /root/.ssh/known_hosts
        owner: root
        group: root
        mode: 0700
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted