---
- import_playbook: install.yml
- hosts: webservers
  remote_user: root
  tasks:
    - name: remove old deployment
      command: rm -Rf /root/javaminion/
    - name: checkout
      git:
        repo: 'git@github.com:nelson54/javaminion.git'
        dest: /root/javaminion
    - name: stop everything
      command: docker-compose down
    - name: start jenkins
      command: docker-compose -f /root/javaminion/docker-compose.yml up jenkins