---
- hosts: webservers
  remote_user: root
  gather_facts: no
  tasks:
  - name: building docker image
    command: docker-compose -f /root/javaminion/docker-compose.yml build --no-cache
  - name: running gradle build
    command: docker-compose -f /root/javaminion/docker-compose.yml run app ./gradlew compileJava