---
- hosts: webservers
  remote_user: root
  gather_facts: no
  tasks:
  - name: building docker image
    command: docker-compose -f /root/javaminion/docker-compose.yml build --no-cache
  - name: starting application
    command: docker-compose -f /root/javaminion/docker-compose.yml up app -d
  - name: compiling java
    command: docker-compose -f /root/javaminion/docker-compose.yml exec app ./gradlew compileJava
