---
- hosts: webservers
  remote_user: root
  tasks:
  - name: stop
    command: docker-compose -f /root/javaminion/docker-compose.yml down
  - name: prune docker
    command: docker system prune --force
  - name: remove old deployment
    file:
      path: /root/javaminion/
      state: absent
