---
- hosts: webservers
  remote_user: root
  gather_facts: no
  tasks:
  - name: checkout
    git:
      repo: 'git@github.com:nelson54/javaminion.git'
      dest: /root/javaminion
      accept_hostkey: yes
  - name: configure gradle
    command: cp /root/javaminion/environments/production/gradle.properties /root/javaminion/