---
- hosts: webservers
  remote_user: root
  gather_facts: no
  tasks:
  - name: checkout
    git:
      repo: 'git@github.com:nelson54/javaminion.git'
      accept_hostkey: yes
      dest: /root/javaminion