---
- hosts: webservers
  remote_user: root
  gather_facts: no
  tasks:
  - name: running javaminion
    command: systemctl start javaminion
    register: checkout
  - debug: var=checkout.stdout_lines