---
- hosts: webservers
  remote_user: root
  gather_facts: no
  tasks:
  - name: start mongo
    command: docker-compose -f /root/javaminion/docker-compose.yml up -d mongo
  - name: testing javaminion
    command: docker-compose -f /root/javaminion/docker-compose.yml exec app ./gradlew test
  - name: copy test log to host
    command: docker cp $(docker ps -a -q -f "name=javaminion_app" | head -n 1):/app/build/reports/tests/test/index.html /root/
  - name: fetching test result html
    fetch:
      src: /root/index.html
      dest: ../logs/test-result.html