---
- hosts: webservers
  remote_user: root
  gather_facts: no
  tasks:
  - name: ensure mongo is stopped
    command: docker-compose -f /root/javaminion/docker-compose.yml stop
  - name: run mongo
    command: docker-compose -f /root/javaminion/docker-compose.yml run -d mongo
  - name: testing javaminion
    command: docker-compose -f /root/javaminion/docker-compose.yml run app bash -c /app/scripts/docker/create-test-archives.sh
    register: testing
  - debug: var=testing.stdout
  - name: copy test-results
    fetch:
      src: /root/archives/test-results.tar.gz
      dest: ../../archives/
  - name: copy test-reports
    fetch:
      src: /root/archives/test-reports.tar.gz
      dest: ../../archives/