---
- hosts: webservers
  remote_user: root
  gather_facts: no
  tasks:
  - name: start mongo
    command: docker-compose -f /root/javaminion/docker-compose.yml up -d mongo
  - name: testing javaminion
    command: docker-compose -f /root/javaminion/docker-compose.yml run app bash -c "./gradlew test && ./scripts/create-test-archives.sh"
    register: checkout
  - debug: var=checkout.stdout
  - name: copy test-results
    fetch:
      src: /root/archives/test-results.tar.gz
      dest: ../../archives/
  - name: copy test-reports
    fetch:
      src: /root/archives/test-reports.tar.gz
      dest: ../../archives/